buildpacks/python: Fix unsupported python runtime detection

diff --git a/buildpacks/python/bin/steps/python b/buildpacks/python/bin/steps/python
--- a/buildpacks/python/bin/steps/python
+++ b/buildpacks/python/bin/steps/python
@@ -29,14 +29,14 @@ if [ ! "$SKIP_INSTALL" ]; then
     # Prepare destination directory.
     mkdir -p $HOME/python
     if ! [ -f $CACHE_DIR/${PYTHON_VERSION}.tar.gz ]; then
-      curl -s -L http://lang-python.s3.amazonaws.com/runtimes/${PYTHON_VERSION}.tar.gz > ${CACHE_DIR}/${PYTHON_VERSION}.tar.gz
-      if [[ $? != 0 ]] ; then
-        puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
-        puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
-        exit 1
-      fi
+      curl -s -L http://lang-python.s3.amazonaws.com/$STACK/runtimes/${PYTHON_VERSION}.tar.gz > ${CACHE_DIR}/${PYTHON_VERSION}.tar.gz
     fi
     tar zxf ${CACHE_DIR}/${PYTHON_VERSION}.tar.gz -C $HOME/python &> /dev/null
+    if [[ $? != 0 ]] ; then
+      puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
+      puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+      exit 1
+    fi
 
   # bpwatch stop install_python
 
