buildpacks/ruby: Show trailing /tmp/build.log lines in case of error
Fixes GH-6

diff --git a/buildpacks/ruby/bin/compile b/buildpacks/ruby/bin/compile
--- a/buildpacks/ruby/bin/compile
+++ b/buildpacks/ruby/bin/compile
@@ -37,6 +37,8 @@ install_ruby() {
 
   mkdir -p /.devstep/.profile.d
   $_rvm env > /.devstep/.profile.d/rvm.sh
+
+  return 0
 }
 
 requires_nodejs() {
@@ -76,7 +78,11 @@ fi
 if [ -d /.devstep/.rvm/rubies/default ]; then
   echo 'Ruby already installed, skipping'
 else
-  install_ruby $2
+  install_ruby $2 || {
+    echo 'Error installing ruby!'
+    tail /tmp/build.log
+    exit 1
+  }
   cat <<-GEMRC > $HOME/.gemrc
 ---
 gem: --no-ri --no-rdoc
