buildpacks/ruby: Improved error output when upgrading bundler

diff --git a/buildpacks/ruby/bin/compile b/buildpacks/ruby/bin/compile
--- a/buildpacks/ruby/bin/compile
+++ b/buildpacks/ruby/bin/compile
@@ -98,8 +98,16 @@ fi
 source /.devstep/.profile.d/rvm.sh
 if $(bundle -v | grep -q '1.5.0'); then
   echo "Bundler 1.5.0 was detected and it is known to have issues with some projects, upgrading to 1.5.2"
-  gem uninstall bundler --force -aIx &>>/tmp/build.log
-  gem install bundler -v 1.5.2 &>>/tmp/build.log
+  gem uninstall bundler --force -aIx &>>/tmp/build.log || {
+    echo 'Error uninstalling bundler!'
+    tail /tmp/build.log
+    exit 1
+  }
+  gem install bundler -v 1.5.2 &>>/tmp/build.log || {
+    echo 'Error upgrading bundler!'
+    tail /tmp/build.log
+    exit 1
+  }
 fi
 
 echo "Installing gems using bundler '$(bundle -v | cut -d' ' -f 3)'..."
