buildpacks/nodejs: Bring in changes from upstream

diff --git a/stack/buildpacks/nodejs/bin/compile b/stack/buildpacks/nodejs/bin/compile
--- a/stack/buildpacks/nodejs/bin/compile
+++ b/stack/buildpacks/nodejs/bin/compile
@@ -1,169 +1,171 @@
 #!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
-set -e            # fail fast
+# set -x
+
+### Configure environment
+
+set -o errexit    # always exit on error
 set -o pipefail   # dont ignore exit codes when piping output
-# set -x          # enable debugging
+set -o nounset    # fail on unset variables
+unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
 
-# Configure directories
-build_dir=$1
-cache_dir=$2/node
-env_dir=$3
+### Configure directories
 
-mkdir -p $cache_dir
+BUILD_DIR=${1:-}
+# CACHE_DIR=${2:-}
+CACHE_DIR=${2:-}/node
+ENV_DIR=${3:-}
+# BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
+bp_basedir="$( cd -P "$( dirname "$0" )" && cd .. && pwd )"
+bp_basedir=$(readlink -f $bp_basedir)
+BP_DIR="${bp_basedir}/heroku-buildpack-nodejs"
+BP_DIR=$(readlink -f $BP_DIR)
 
-bp_dir=$(cd $(dirname $0); cd ..; pwd)
+mkdir -p $CACHE_DIR
 
-# Load some convenience functions like status(), echo(), and indent()
-source $bp_dir/bin/common.sh
+mkdir -p "$BUILD_DIR/.heroku/node/"
+cd $BUILD_DIR
+export PATH="$BUILD_DIR/.heroku/node/bin":$PATH
 
-# Output npm debug info on error
-trap cat_npm_debug_log ERR
+### Load dependencies
 
-if [ -d ${HOME}/nodejs ]; then
-  echo 'Node.js already installed, skipping'
-else
+source $BP_DIR/lib/output.sh
+source $BP_DIR/lib/json.sh
+source $BP_DIR/lib/failure.sh
+# source $BP_DIR/lib/environment.sh
+source $bp_basedir/lib/environment.sh
+# source $BP_DIR/lib/binaries.sh
+source $bp_basedir/lib/binaries.sh
+# source $BP_DIR/lib/cache.sh
+# source $BP_DIR/lib/dependencies.sh
+source $bp_basedir/lib/dependencies.sh
 
-###############################################################################
-# Indentation is intentionally weird here in order to make our lives easier when
-# bringing in updates from the official heroku buildpack
+### Handle errors
 
-# Look in package.json's engines.node field for a semver range
-if [ -f $build_dir/package.json ]; then
-  semver_range=$(cat $build_dir/package.json | ${DEVSTEP_BIN}/jq -r .engines.node)
-else
-  semver_range=
-fi
-
-# Resolve node version using semver.io
-_node_version() {
-  curl --connect-timeout 30 --silent --get --data-urlencode "range=${semver_range}" https://semver.io/node/resolve || {
-    echo '       Unable to fetch node version from semver.io, using latest known (0.10.35)' >&2
-    echo '0.10.35'
-  }
+handle_failure() {
+  header "Build failed"
+  failure_message | indent
 }
-node_version=$(_node_version)
+trap 'handle_failure' ERR
 
-# Recommend using semver ranges in a safe manner
-if [ "$semver_range" == "null" ]; then
-  protip "Specify a node version in package.json"
-  semver_range=""
-elif [ "$semver_range" == "*" ]; then
-  protip "Avoid using semver ranges like '*' in engines.node"
-elif [ ${semver_range:0:1} == ">" ]; then
-  protip "Avoid using semver ranges starting with '>' in engines.node"
-fi
+### Check initial state
 
-# Output info about requested range and resolved node version
-if [ "$semver_range" == "" ]; then
-  status "Defaulting to latest stable node: $node_version"
-else
-  status "Requested node range:  $semver_range"
-  status "Resolved node version: $node_version"
-fi
+[ -e "$BUILD_DIR/node_modules" ] && PREBUILD=true || PREBUILD=false
 
-# Download node from Heroku's S3 mirror of nodejs.org/dist
-tarball="node-v$node_version-linux-x64.tar.gz"
-tarball_path="$cache_dir/node-v$node_version-linux-x64.tar.gz"
-if [ -f $tarball_path ]; then
-  status "Using cached tarball"
-else
-  status "Downloading and installing node"
-  node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
-  curl $node_url > $tarball_path
-fi
-mkdir -p ${HOME}/nodejs
-tar xzf $tarball_path -C ${HOME}/nodejs --strip-components=1
+### Failures that should be caught immediately
 
-export PATH="${HOME}/nodejs/bin:$build_dir/node_modules/.bin:$PATH"
-export NODE_PATH="${HOME}/nodejs/lib/node_modules:"
+fail_invalid_package_json "$BUILD_DIR"
+# warn_prebuilt_modules "$BUILD_DIR"
+warn_missing_package_json "$BUILD_DIR"
 
-# Update the PATH
-status "Building runtime environment"
-echo "export PATH=\"\$HOME/nodejs/bin:$build_dir/node_modules/.bin:\$PATH\";" > ${HOME}/.profile.d/nodejs.sh
-echo "export NODE_PATH=\"\$HOME/nodejs/lib/node_modules:\";" >> ${HOME}/.profile.d/nodejs.sh
-###############################################################################
-fi
+### Compile
 
-# Cache npm packages on host machine
-npm config set cache $cache_dir/npm
+create_env() {
+  # write_profile "$BP_DIR" "$BUILD_DIR"
+  # write_profile "$BP_DIR" "$HOME"
+  write_export "$BP_DIR" "$BUILD_DIR"
+  # export_env_dir "$ENV_DIR"
+  create_default_env
+}
 
-# Run subsequent node/npm commands from the build path
-cd $build_dir
+header "Creating runtime environment"
+create_env # can't indent the whole thing because piping causes subshells; no exporting possible
+list_node_config | indent
 
-# XXX: Is this needed?
-# If node_modules directory is checked into source control then
-# rebuild any native deps. Otherwise, restore from the build cache.
-# if test -d $build_dir/node_modules; then
-#   status "Found existing node_modules directory; skipping cache"
-#   status "Rebuilding any native dependencies"
-#   npm rebuild 2>&1 | indent
-# elif test -d $cache_dir/node/node_modules; then
-#   status "Restoring node_modules directory from cache"
-#   cp -r $cache_dir/node/node_modules $build_dir/
+install_bins() {
+  local node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
+  local iojs_engine=$(read_json "$BUILD_DIR/package.json" ".engines.iojs")
+  local npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
+
+  if [ -n "$iojs_engine" ]; then
+    echo "engines.iojs (package.json):  $iojs_engine (iojs)"
+  else
+    echo "engines.node (package.json):  ${node_engine:-unspecified}"
+  fi
+  echo "engines.npm (package.json):   ${npm_engine:-unspecified (use default)}"
+  echo ""
+
+  if [ -n "$iojs_engine" ]; then
+    warn_node_engine "$iojs_engine"
+    # install_iojs "$iojs_engine" "$BUILD_DIR/.heroku/node"
+    install_iojs "$iojs_engine" "$HOME/node" "$CACHE_DIR"
+  else
+    warn_node_engine "$node_engine"
+    # install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
+    install_nodejs "$node_engine" "$HOME/node" "$CACHE_DIR"
+  fi
+  # install_npm "$npm_engine" "$BUILD_DIR/.heroku/node"
+  for f in $HOME/.profile.d/*.sh; do
+    source $f
+  done
+  install_npm "$npm_engine" "$HOME/node" "$CACHE_DIR"
+  warn_old_npm
+}
+
+header "Installing binaries"
+install_bins | indent
+
+# restore_cache() {
+#   local cache_status=$(get_cache_status)
 #
-#   status "Pruning cached dependencies not specified in package.json"
-#   npm prune 2>&1 | indent
-#
-#   if test -f $cache_dir/node/.heroku/node-version && [ $(cat $cache_dir/node/.heroku/node-version) != "$node_version" ]; then
-#     status "Node version changed since last build; rebuilding dependencies"
-#     npm rebuild 2>&1 | indent
+#   if [ "$cache_status" == "disabled" ]; then
+#     echo "Skipping (cache disabled)"
+#   elif [ "$cache_status" == "invalidated" ]; then
+#     echo "Skipping (cache invalidated)"
+#   else
+#     local cache_directories=$(get_cache_directories)
+#     if [ "$cache_directories" == "" ]; then
+#       echo "Loading 1 from cacheDirectories (default):"
+#       restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" "node_modules"
+#     else
+#       echo "Loading $(echo $cache_directories | wc -w | xargs) from cacheDirectories (package.json):"
+#       restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
+#     fi
 #   fi
+# }
 #
-# fi
+# header "Restoring cache"
+# restore_cache | indent
 
-# Handle npm's new cert bug
-# http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more
-# if [ ! -f "$build_dir/.npmrc" ]; then
-#   status "Writing a custom .npmrc to circumvent npm bugs"
-#   echo "ca=" > "$build_dir/.npmrc"
-# fi
+for f in $HOME/.profile.d/*.sh; do
+  source $f
+done
+# Cache npm packages on host machine
+npm config set cache $CACHE_DIR/npm
 
-if [ -f package.json ]; then
-  status "Installing dependencies"
-  npm install 2>&1 | indent
-fi
-
-if [ -f bower.json ]; then
-  if ! [ -f $build_dir/node_modules/.bin/bower ]; then
-    status "Installing bower"
-    npm install bower 2>&1 | indent
+build_dependencies() {
+  if $PREBUILD; then
+    echo "Prebuild detected (node_modules already exists)"
+    rebuild_node_modules "$BUILD_DIR"
+  else
+    install_node_modules "$BUILD_DIR"
   fi
-  status "Installing bower dependencies"
-  $build_dir/node_modules/.bin/bower install 2>&1 | indent
-fi
+}
 
-if [ -f Gruntfile.js ]; then
-  if ! [ -f $build_dir/node_modules/.bin/grunt ]; then
-    status "Installing grunt"
-    npm install grunt-cli 2>&1 | indent
-  fi
-fi
+header "Building dependencies"
+build_dependencies | indent
 
-# Persist goodies like node-version in the slug
-# \mkdir -p $build_dir/.heroku
+# cache_build() {
+#   local cache_directories=$(get_cache_directories)
+#   echo "Clearing previous node cache"
+#   clear_cache
+#   if [ "$cache_directories" == "" ]; then
+#     echo "Saving 1 cacheDirectories (default):"
+#     save_cache_directories "$BUILD_DIR" "$CACHE_DIR" "node_modules"
+#   else
+#     echo "Saving $(echo $cache_directories | wc -w | xargs) cacheDirectories (package.json):"
+#     save_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
+#   fi
+# }
 
-# Save resolved node version in the slug for later reference
-# echo $node_version > $build_dir/.heroku/node-version
+# header "Caching build"
+# cache_build | indent
 
-# XXX: Is this needed?
-# Purge node-related cached content, being careful not to purge the top-level
-# cache, for the sake of heroku-buildpack-multi apps.
-# rm -rf $cache_dir/node_modules # (for apps still on the older caching strategy)
-# rm -rf $cache_dir/node
-# mkdir -p $cache_dir/node
+summarize_build() {
+  cd $BUILD_DIR
+  (npm ls --depth=0 | tail -n +2 || true) 2>/dev/null
+}
 
-# XXX: Is this needed?
-# If app has a node_modules directory, cache it.
-# if test -d $build_dir/node_modules; then
-#   status "Caching node_modules directory for future builds"
-#   cp -r $build_dir/node_modules $cache_dir/node
-# fi
-
-# XXX: Is this needed?
-# Copy goodies to the cache
-# cp -r $build_dir/.heroku $cache_dir/node
-
-# XXX: Is this needed?
-# status "Cleaning up node-gyp and npm artifacts"
-# rm -rf "$build_dir/.node-gyp"
-# rm -rf "$build_dir/.npm"
+header "Build succeeded!"
+summarize_build | indent
